DEFAULT_IMAGE_SIZE = 320
DEFAULT_DATASET_NAME = "detection-datasets/coco"
DEFAULT_MODEL_REPO_ID = "zhong/ssd-mobilenet-models"
DEFAULT_ONNX_OPSET_VERSION = 11
HYBRID_MOBILENETV4_ONNX_OPSET_VERSION = 14
